In [2]:
import numpy as np
list1=[1,2,3,4,5,6,7,8]
print(list1)
print(list1[2])

[1, 2, 3, 4, 5, 6, 7, 8]
3


In [5]:
list2=([23,'india','rohan',list1])
print(list2)

[23, 'india', 'rohan', [1, 2, 3, 4, 5, 6, 7, 8]]


In [7]:
np1=np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
print(np1.shape)


[0 1 2 3 4 5 6 7 8 9]
(10,)


In [10]:
np2=np.arange(0,10,3)#step
print(np2)
np3=np.zeros(20)
print(np3)

[0 3 6 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
np4=np.zeros((2,5))#((row,colm))
print(np4)
np5=np.full((10),6)#((row)
print(np5)
np6=np.full((5,6),7)
print(np6)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[6 6 6 6 6 6 6 6 6 6]
[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]
